development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ewdaemcdrjgpjc:taFBfYoXdfl5yOc33sfWVNgDxn@ec2-54-243-212-122.compute-1.amazonaws.com:5432/db7lvlbve3pnha
